---
# This is the holiday sensor. This binary sensor tells me if it is
# a national holiday today.
#
# This is pretty useful for a lot of automations.
#
# https://www.home-assistant.io/integrations/workday/
#
binary_sensor:
  - platform: workday
    name: holiday
    country: DE
    province: NI
    workdays:
      - holiday
    excludes: []
  # TODO: Move to template sensor
  - platform: workday
    name: workday
    country: DE
    province: NI
    workdays:
      - mon
      - tue
      - wed
      - thu
      - fri
