---
#
# Saeubert die DB einmal alle 30 Minuten.
#
alias: system_recorder_purge
description: Purge recorder database
id: 7cce89e8-662c-4e2d-9e56-5b76cc8adb66
mode: single
trigger:
  - platform: time_pattern
    minutes: 30
action:
  - service: recorder.purge
