---
#
# Jeden Sonntag die DB einmal aufräumen
#
alias: system_recorder_repack
description: Repack recorder database
id: 752639e0-9527-45a6-84e8-f54537d40278
mode: single
trigger:
  - platform: time
    at: "05:55"
condition:
  - condition: time
    weekday:
      - sun
action:
  - service: recorder.purge
    data:
      repack: true
