---
description: Send notification on Home Assistant start
alias: system_start_notification
id: 104463f6-7524-48d9-bbe5-2bb09017e946
mode: single
trigger:
  platform: homeassistant
  event: start
action:
  - service: notify.matthias_signal
    data:
      message: Alle meine Prozesse sind neu gestartet!
